languageCode = "fr"
languageName = "Francais"
displayName = "FR"
isoCode = "fr"
weight = 1
rtl = false

title = "samsepi0l"
logo = "img/mikasa-round.png"
# secondaryLogo = "img/secondary-logo.png"
# description = "My awesome website"
copyright = "CC BY-SA 4.0 { year }"

dateFormat = "2 January 2006"

[author]
  name = "samsepi0l"
  image = "img/mikasa.jpg"
  headline = "Le blog d'un fan (abusif) de Mr. Robot"
  bio = "Le blog d'un fan (abusif) de Mr. Robot"
  links = [
    { envelope = "mailto:contact@samsepi0l.dev" },
    { email = "https://matrix.to/#/@samsepi0l:projectsegfau.lt" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/d4rklynk" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/username" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
#     { linkedin = "https://linkedin.com/in/username" },
#     { lock = "samsepi0l.crt" },
#     { matrix = "https://matrix.to/#/@samsepi0l:arcticfoxes.net" },
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
    { pgpkey = "/public-pgp-key.asc"},
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
    { rss = "https://samsepi0l.dev/index.xml"},
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
#     { soundcloud = "https://soundcloud.com/username" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
    { twitter = "https://twitter.com/samsepi0l753" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
  ]
