# netlify.toml

#[build]
#  command = "hugo server"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.20.4"
  TZ = "Europe/Paris"  # Set to preferred timezone

[context.production.environment]
  HUGO_VERSION = "0.112.0"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.112.0"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"
