# netlify.toml

[build]
  command = "hugo --gc -b $URL"
  publish = "public"

[build.environment]
  NODE_ENV = "production"
  GO_VERSION = "1.20.4"
  TZ = "Europe/Paris"  # Set to preferred timezone

[context.production.environment]
  HUGO_VERSION = "0.120.1"
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.120.1"
