name: Update Hugo Version

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  update_hugo_version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update Hugo Version
        env:
          CI_COMMIT_AUTHOR: samsepi0l
          CI_COMMIT_AUTHOR_EMAIL: contact@simpleprivacy.fr
        run: bash update_hugo.sh
