name: Update Hugo
on:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  update_hugo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run update_hugo.sh script
        run: |
          chmod +x update_hugo.sh
          ./update_hugo.sh
