name: Update Hugo Version

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  update_hugo_version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update Hugo Version
        run: bash update_hugo_version.sh
