# This workflow executes a Ruby script to check for new updates for the latest hugo version. If a new update has been found, then the script parse the version from GitHub releases then edit the netlify.toml file to update the HUGO_VERSION variable.
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  #
  # Triggers the workflow on every 0th, 3rd, 6th, 9th, 12th, 15th, 18th, and 21st hour
  schedule:
    - cron: "0 0,3,6,9,12,15,18,21 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          node-version: '16'

      # Runs a single command using the runners shell
      - name: Update the netlify.toml file to the latest hugo version
        env:
          CI_COMMIT_AUTHOR: samsepi0l
          CI_COMMIT_AUTHOR_EMAIL: contact@simpleprivacy.fr
        run: ruby udpate_hugo.rb

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script 
      #  run: |
      #    echo "Hello world!"
